# note: added some packages through pip install
# and did a `pre-commit install` http://pre-commit.com/
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
#    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.16.3
    hooks:
    -   id: yapf
